### ISSUE TITLE
Create a standard modules install script

### ISSUE THREAD

**Issue by ghost** [ibabushkin/wormbot#1]
Write a bash script that pulls some (later defined) standard modules from github, compiles and moves them to the scripts directory.

**Comment by ibabushkin** [comment]
This is a rather good idea, basically a plugin management system on ~~steroids~~ sleeping pills.

**Comment by ibabushkin** [comment]
I addressed the issue by creating a separate [repository](https://www.github.com/ibabushkin/wormbot-scripts). A simple git pull should implement the requested functionality.
