### ISSUE TITLE
Love module (<3)

### ISSUE THREAD

**Issue by kh0fo** [ibabushkin/wormbot#2]
The issue is that the module interprets the `:3` as `<3`
and thus returns this

```
#test
<khofo> :3
<wormbot> luv you, 
<khofo> :3 khofo
<wormbot> luv you, khofo
```

I tried other symbols, but it did not operate in the same manner

```
#test
<khofo> !3
<khofo> @3
<khofo> #3
<khofo> "3
<khofo> ?3
<khofo> >3
<khofo> ;3
<khofo> =3
<khofo> +3
<khofo> -3
<khofo> _3
<khofo> )3
<khofo> (3
<khofo> *3
<khofo> &3
<khofo> ^3
<khofo> %3
<khofo> $3
<khofo> '3
<khofo> "3
```

I would have looked at the code, but the repo is not updated with it, what's weird is that any other symbol did not work, I am wondering about how the script is written

**Comment by ibabushkin** [comment]
This is not an issue with the script but with the fact that we interpret multiple prefixes, including `<` and `:`. That's why you can use `<3` as a command _at all_. We'd need to decide what to do about that behaviour.

Right now we use this:

``` Haskell
-- prefix for normal commands
commandPrefixes :: String
commandPrefixes = ":<|.\\"
```

**Comment by ibabushkin** [comment]
As discussion on IRC showed, it is probably best to pass the prefix used to invoke a command to the corresponding script via an environment variable `PREFIX` (or similar), as this is simple enough and versatile. In a similar manner we could add channel information etc. if such data is needed in the future.

Thus, I will implement this functionality, and address similar ideas when the scheduled rewrite of wormbot starts.

**Comment by ibabushkin** [comment]
Issue is now fixed. A new environment variable `PREFIX` has been added, some scripts have been improved as well.
