### ISSUE TITLE
DuckDuckGo Module

### ISSUE THREAD

**Issue by kh0fo** [ibabushkin/wormbot#3]
When `:d` is issued my any user on irc, the DuckDuckGo Module runs and delivers an empty link

```
#test
<khofo> :d
<wormbot> https://duckduckgo.com/?q=
<EZBot> Title: [ DuckDuckGo ]
```

A solution to this would be to make sure the modules runs only if `arg_after_:d != " "`

**Comment by ibabushkin** [comment]
yes, I will fix this issue this evening

**Comment by ibabushkin** [comment]
Fixed it.
